[opener]
  edit = [
	{ run = '${EDITOR:-helix} "$@"', desc = "$EDITOR", block = true, for = "unix" }
]

okular = [
    { run = 'okular "$@"', desc = "Okular (PDF)", orphan = true, for = "unix" }
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = "okular" },
    { mime = "image/*", use = "okular"}
]
